# Generated by Django 4.2.4 on 2024-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_book_cover_book_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
    ]
